give more helpful error messages for SGX_MODE and IAS_MODE settings
Many projects submodule mobilecoin.git and do not have it's BUILD.md
document which describes how to set these variables.

It frequently happens that newly onboarded developers, or partners
like copper, run into a build error that looks like this:

```
   Compiling libp2p-plaintext v0.37.0
   Compiling libp2p-floodsub v0.40.1
   Compiling slog-envlogger v2.2.0
error: failed to run custom build command for `mc-attest-core v4.0.2 (/home/chris/mobilecoinofficial/deqs/mobilecoin/attest/core)`

Caused by:
  process didn't exit successfully: `/home/chris/mobilecoinofficial/deqs/target/debug/build/mc-attest-core-fa6d778110b3deb5/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Could not parse SGX environment: Variable(NotPresent)', mobilecoin/attest/core/build.rs:8:41
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This error doesn't contain enough information for them to understand
and fix the problem, so they end up asking us for help.

We can follow the rust tradition of trying to make build-time errors
contain enough information to understand how to address the problem.

This commit tries to make the message say what variable was not present,
and also contain a link to the mobilecoin.git BUILD.md so that they can
learn more.