Fix deprecation warning (protobuf) (#693)
* fix deprecation warning about protobuf::parse_from_bytes

The deprecation warning that I saw was like this:

```
error: use of deprecated item 'protobuf::message::parse_from_bytes': Use Message::parse_from_bytes instead
 --> /tmp/mobilenode/public/api/src/display.rs:9:16
  |
9 | use protobuf::{parse_from_bytes, Message};
  |                ^^^^^^^^^^^^^^^^
  |
  = note: `-D deprecated` implied by `-D warnings`

error: use of deprecated item 'protobuf::message::parse_from_bytes': Use Message::parse_from_bytes instead
  --> /tmp/mobilenode/public/api/src/display.rs:64:23
   |
64 |         let wrapper = parse_from_bytes(&wrapper_bytes)
   |                       ^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

error: could not compile `mc-api`.
```

This happened with protobuf 2.20

* move to protobuf 2.20 and fix deprecation warning about parse_from_bytes

When trying to move android-bindings and libmobilecoin into their
own workspace (to allow configuration for smaller binaries), I got
errors in mc-api due to deprecation warnings added by protobuf 2.20.

This uprevs protobuf to 2.20 and fixes all deprecation warnings in
the public repo.